#!/bin/sh

# Goto the build directory
mkdir debug
cd debug

# Clean-up any previous CMake invocation
rm -rf CMakeCache.txt

# Set-up the environment
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++ 

# Re-run CMake
cmake CMakeLists.txt
